<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.33">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>8&nbsp; Emission Factors – Spatial Analysis in R for Forest Carbon Verification</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./activity-data.html" rel="next">
<link href="./allometry.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ea385d0e468b0dd5ea5bf0780b1290d9.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-352c1c0ff19b8228249a899e5c7e3202.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
<meta property="og:title" content="8&nbsp; Emission Factors – Spatial Analysis in R for Forest Carbon Verification">
<meta property="og:description" content="">
<meta property="og:site_name" content="Spatial Analysis in R for Forest Carbon Verification">
</head>
<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./emission-factors.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Emission Factors</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Course Contents</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/seamusrobertmurphy/training-rspatial" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-getting-started.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Getting Started</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-vector-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Vector Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-raster-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Raster Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-terrain-hydrology.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Terrain and Hydrology</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-lidar-point-clouds.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">LiDAR and Point Clouds</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-disturbance-risk.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Disturbance and Risk</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./allometry.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Allometry and Biomass</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./emission-factors.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Emission Factors</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./activity-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Activity Data and Classification</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-uncertainty.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Uncertainty</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-time-series.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Time Series</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-spatial-patterns.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Spatial Patterns</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./A-automation-registries.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Automation, Protocols and Registries</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">References</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title"><strong>On this page</strong></h2>
   
  <ul>
<li><a href="#the-other-half-of-the-identity" id="toc-the-other-half-of-the-identity" class="nav-link active" data-scroll-target="#the-other-half-of-the-identity"><span class="header-section-number">8.1</span> The other half of the identity</a></li>
  <li><a href="#tiers" id="toc-tiers" class="nav-link" data-scroll-target="#tiers"><span class="header-section-number">8.2</span> Tiers</a></li>
  <li><a href="#where-the-default-factors-come-from" id="toc-where-the-default-factors-come-from" class="nav-link" data-scroll-target="#where-the-default-factors-come-from"><span class="header-section-number">8.3</span> Where the default factors come from</a></li>
  <li><a href="#the-stock-difference-method" id="toc-the-stock-difference-method" class="nav-link" data-scroll-target="#the-stock-difference-method"><span class="header-section-number">8.4</span> The stock-difference method</a></li>
  <li><a href="#the-asymmetry-nobody-mentions" id="toc-the-asymmetry-nobody-mentions" class="nav-link" data-scroll-target="#the-asymmetry-nobody-mentions"><span class="header-section-number">8.5</span> The asymmetry nobody mentions</a></li>
  <li><a href="#propagating-the-uncertainty" id="toc-propagating-the-uncertainty" class="nav-link" data-scroll-target="#propagating-the-uncertainty"><span class="header-section-number">8.6</span> Propagating the uncertainty</a></li>
  <li><a href="#where-the-uncertainty-actually-lives" id="toc-where-the-uncertainty-actually-lives" class="nav-link" data-scroll-target="#where-the-uncertainty-actually-lives"><span class="header-section-number">8.7</span> Where the uncertainty actually lives</a></li>
  <li><a href="#what-the-imprecision-costs" id="toc-what-the-imprecision-costs" class="nav-link" data-scroll-target="#what-the-imprecision-costs"><span class="header-section-number">8.8</span> What the imprecision costs</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">8.9</span> Exercises</a></li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/seamusrobertmurphy/training-rspatial/edit/main/emission-factors.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/seamusrobertmurphy/training-rspatial/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">
<span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Emission Factors</span>
</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><section id="the-other-half-of-the-identity" class="level2" data-number="8.1"><h2 data-number="8.1" class="anchored" data-anchor-id="the-other-half-of-the-identity">
<span class="header-section-number">8.1</span> The other half of the identity</h2>
<p>Almost every greenhouse gas estimate in land use reduces to one multiplication:</p>
<p><span class="math display">\[\text{Emissions} = \text{Activity Data} \times \text{Emission Factor}\]</span></p>
<p>Activity data is the extent of something happening: hectares deforested, hectares converted, hectares under a new management regime. The emission factor is the greenhouse gas consequence per unit of that activity. The previous chapters have been about the left-hand term, because that is where spatial analysis lives. This chapter is about the right-hand one, which is where most of the money and most of the uncertainty actually sit.</p>
<p>The distinction matters more than it looks. An analyst who maps deforestation to the pixel and then multiplies by a factor pulled from a default table has spent all their effort on the term they measured and none on the term they assumed. The factor is usually the larger source of error, and unlike the map it cannot be improved by better imagery.</p>
</section><section id="tiers" class="level2" data-number="8.2"><h2 data-number="8.2" class="anchored" data-anchor-id="tiers">
<span class="header-section-number">8.2</span> Tiers</h2>
<p>The IPCC organises methods into three tiers, and the tier is a statement about where the numbers came from rather than about how sophisticated the arithmetic is <span class="citation" data-cites="ipcc2006gl">(<a href="references/index.html#ref-ipcc2006gl" role="doc-biblioref">IPCC, 2006</a>)</span>.</p>
<p><strong>Tier 1</strong> uses global or regional default factors published in the guidelines, applied through simple equations, with default assumptions about what happens after a land-use change. It requires no local measurement beyond the activity data. It is the fallback when nothing better exists, and its uncertainties are correspondingly wide.</p>
<p><strong>Tier 2</strong> keeps the Tier 1 equations but substitutes country-specific or region-specific factors derived from local measurement. This is where most credible national inventories sit.</p>
<p><strong>Tier 3</strong> replaces the equations themselves with models or direct measurement systems, calibrated and validated locally.</p>
<p>The tiers are not a quality ladder in the sense that Tier 1 is wrong. A well-applied Tier 1 estimate with an honest uncertainty is more defensible than a Tier 3 model whose calibration nobody can reproduce. What the tiers do determine is the size of the interval you must report, and therefore the deduction you must accept.</p>
</section><section id="where-the-default-factors-come-from" class="level2" data-number="8.3"><h2 data-number="8.3" class="anchored" data-anchor-id="where-the-default-factors-come-from">
<span class="header-section-number">8.3</span> Where the default factors come from</h2>
<p>The Tier 1 defaults are not conjured. They are meta-analyses of published soil and biomass measurements, and the guidelines publish their sample sizes and confidence limits alongside the means. Reading those columns is the single most useful habit in factor selection, because the stated uncertainty varies by more than an order of magnitude across the same table.</p>
<p>This is an extract from the reference soil organic carbon stocks of the 2019 Refinement <span class="citation" data-cites="ipcc2019refinement">(<a href="references/index.html#ref-ipcc2019refinement" role="doc-biblioref">IPCC, 2019</a>, Table 2.3)</span>, which are derived from a global soil profile compilation <span class="citation" data-cites="batjes2011">(<a href="references/index.html#ref-batjes2011" role="doc-biblioref">Batjes, 2011</a>)</span>. The full table covers ten climate zones by six soil classes; these are seven cells of it.</p>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">soc_ref</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span></span>
<span>  climate <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Cool temperate moist"</span>, <span class="st">"Cool temperate moist"</span>, <span class="st">"Warm temperate dry"</span>,</span>
<span>              <span class="st">"Tropical moist"</span>, <span class="st">"Tropical moist"</span>, <span class="st">"Tropical dry"</span>, <span class="st">"Boreal moist/dry"</span><span class="op">)</span>,</span>
<span>  soil    <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"HAC"</span>, <span class="st">"Sandy"</span>, <span class="st">"HAC"</span>, <span class="st">"HAC"</span>, <span class="st">"LAC"</span>, <span class="st">"LAC"</span>, <span class="st">"Sandy"</span><span class="op">)</span>,</span>
<span>  socref  <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">81</span>, <span class="fl">51</span>, <span class="fl">24</span>, <span class="fl">40</span>, <span class="fl">38</span>, <span class="fl">19</span>, <span class="fl">10</span><span class="op">)</span>,      <span class="co"># tonnes C / ha, 0-30 cm</span></span>
<span>  unc_pct <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">5</span>, <span class="fl">13</span>, <span class="fl">5</span>, <span class="fl">7</span>, <span class="fl">5</span>, <span class="fl">10</span>, <span class="fl">90</span><span class="op">)</span>,          <span class="co"># 95% limit, % of mean</span></span>
<span>  n       <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">334</span>, <span class="fl">126</span>, <span class="fl">781</span>, <span class="fl">226</span>, <span class="fl">326</span>, <span class="fl">135</span>, <span class="cn">NA</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu">knitr</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable</a></span><span class="op">(</span><span class="va">soc_ref</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: left;">climate</th>
<th style="text-align: left;">soil</th>
<th style="text-align: right;">socref</th>
<th style="text-align: right;">unc_pct</th>
<th style="text-align: right;">n</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Cool temperate moist</td>
<td style="text-align: left;">HAC</td>
<td style="text-align: right;">81</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">334</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cool temperate moist</td>
<td style="text-align: left;">Sandy</td>
<td style="text-align: right;">51</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">126</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Warm temperate dry</td>
<td style="text-align: left;">HAC</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">781</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tropical moist</td>
<td style="text-align: left;">HAC</td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">226</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tropical moist</td>
<td style="text-align: left;">LAC</td>
<td style="text-align: right;">38</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">326</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tropical dry</td>
<td style="text-align: left;">LAC</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">135</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Boreal moist/dry</td>
<td style="text-align: left;">Sandy</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">90</td>
<td style="text-align: right;">NA</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Look at the last row against the third. Warm temperate dry soils with high activity clay are stated as 24 tonnes per hectare with a 95 per cent limit of five per cent, resting on 781 measured profiles. Boreal sandy soils are stated as 10 tonnes per hectare with a limit of ninety per cent, resting on no profiles at all: that figure is a nominal error assigned because no data were available, carried forward from the 1996 guidelines.</p>
<p>Those two entries look identical in a spreadsheet. They are epistemically unrelated. One is a well-estimated mean; the other is a placeholder with an honesty marker attached. A project whose stratification lands it in the second cell is in a different position from one that lands in the first, and no amount of downstream care recovers the difference.</p>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>worst_to_best_ratio <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span><span class="op">(</span><span class="va">soc_ref</span><span class="op">$</span><span class="va">unc_pct</span><span class="op">)</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">min</a></span><span class="op">(</span><span class="va">soc_ref</span><span class="op">$</span><span class="va">unc_pct</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; worst_to_best_ratio </span></span>
<span><span class="co">#&gt;                  18</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The stated uncertainty spans eighteenfold within a single table. Factor selection is therefore not a lookup; it is a decision about which of these positions you are willing to defend.</p>
</section><section id="the-stock-difference-method" class="level2" data-number="8.4"><h2 data-number="8.4" class="anchored" data-anchor-id="the-stock-difference-method">
<span class="header-section-number">8.4</span> The stock-difference method</h2>
<p>Soil carbon is the pool where Tier 1 methods have changed most. The 2006 guidelines assumed that converting land oxidised its soil carbon immediately. The 2019 Refinement replaces that with a linear transition to a new equilibrium spread over a default twenty years, computed as a difference between two stock estimates <span class="citation" data-cites="ipcc2019refinement">(<a href="references/index.html#ref-ipcc2019refinement" role="doc-biblioref">IPCC, 2019</a>, Eq. 2.25)</span>:</p>
<p><span class="math display">\[\Delta C_{Mineral} = \frac{SOC_0 - SOC_{(0-T)}}{D}\]</span></p>
<p>where <span class="math inline">\(SOC_0\)</span> is the stock in the final year of the inventory period, <span class="math inline">\(SOC_{(0-T)}\)</span> the stock at its beginning, and <span class="math inline">\(D\)</span> the time dependence of the stock change factors, twenty years under Tier 1. Each stock is itself built from a reference value and three dimensionless factors:</p>
<p><span class="math display">\[SOC = SOC_{REF} \times F_{LU} \times F_{MG} \times F_{I}\]</span></p>
<p><span class="math inline">\(F_{LU}\)</span> is the land use factor, <span class="math inline">\(F_{MG}\)</span> the management factor, and <span class="math inline">\(F_I\)</span> the input factor, each a multiplier relative to the native reference condition. All are defined for a 30 cm depth, because that is the depth the reference stocks were compiled at, and mixing a factor from one depth convention with a stock from another is a common and invisible error.</p>
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">socref</span> <span class="op">&lt;-</span> <span class="fl">38</span>      <span class="co"># tropical moist, LAC</span></span>
<span><span class="va">f_lu</span>   <span class="op">&lt;-</span> <span class="fl">0.83</span>    <span class="co"># forest to long-term cultivated</span></span>
<span><span class="va">f_mg</span>   <span class="op">&lt;-</span> <span class="fl">1.00</span>    <span class="co"># full tillage</span></span>
<span><span class="va">f_i</span>    <span class="op">&lt;-</span> <span class="fl">0.94</span>    <span class="co"># low input</span></span>
<span></span>
<span><span class="va">soc_new</span>    <span class="op">&lt;-</span> <span class="va">socref</span> <span class="op">*</span> <span class="va">f_lu</span> <span class="op">*</span> <span class="va">f_mg</span> <span class="op">*</span> <span class="va">f_i</span></span>
<span><span class="va">annual_c</span>   <span class="op">&lt;-</span> <span class="op">(</span><span class="va">soc_new</span> <span class="op">-</span> <span class="va">socref</span><span class="op">)</span> <span class="op">/</span> <span class="fl">20</span></span>
<span><span class="va">annual_co2</span> <span class="op">&lt;-</span> <span class="va">annual_c</span> <span class="op">*</span> <span class="fl">44</span> <span class="op">/</span> <span class="fl">12</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>soc_before <span class="op">=</span> <span class="va">socref</span>, soc_after <span class="op">=</span> <span class="va">soc_new</span>,</span>
<span>        tC_ha_yr <span class="op">=</span> <span class="va">annual_c</span>, tCO2e_ha_yr <span class="op">=</span> <span class="va">annual_co2</span><span class="op">)</span>, <span class="fl">3</span><span class="op">)</span></span>
<span><span class="co">#&gt;  soc_before   soc_after    tC_ha_yr tCO2e_ha_yr </span></span>
<span><span class="co">#&gt;      38.000      29.648      -0.418      -1.531</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The chain matters more than any single link. Three multiplicative factors mean three opportunities for a stratification error, and because they multiply, a mistake in any one of them scales the whole result rather than adding to it.</p>
</section><section id="the-asymmetry-nobody-mentions" class="level2" data-number="8.5"><h2 data-number="8.5" class="anchored" data-anchor-id="the-asymmetry-nobody-mentions">
<span class="header-section-number">8.5</span> The asymmetry nobody mentions</h2>
<p>Tier 1 does not treat gains and losses alike. Carbon <em>increases</em> are spread over the twenty-year transition; carbon <em>losses</em> from dead organic matter on conversion are assigned to a single year <span class="citation" data-cites="ipcc2019refinement">(<a href="references/index.html#ref-ipcc2019refinement" role="doc-biblioref">IPCC, 2019, p. s.2.3.2</a>)</span>. That asymmetry is deliberate and conservative: it credits slowly and debits fast.</p>
<p>It also has a practical consequence for anyone comparing a project’s numbers against an inventory. A project reporting a gain over five years captures a quarter of the eventual stock change, not all of it, and a project reporting a conversion loss books the whole thing at once. Two projects with identical biophysical outcomes and different timings will report very different annual figures, entirely legitimately.</p>
</section><section id="propagating-the-uncertainty" class="level2" data-number="8.6"><h2 data-number="8.6" class="anchored" data-anchor-id="propagating-the-uncertainty">
<span class="header-section-number">8.6</span> Propagating the uncertainty</h2>
<p>Each factor in the chain carries its own uncertainty, and they combine. For independent terms entering a product, the proportional uncertainties combine in quadrature:</p>
<p><span class="math display">\[U_{total} = \sqrt{U_1^2 + U_2^2 + \dots + U_n^2}\]</span></p>
<p>Take a silvopastoral project on a thousand hectares, with the uncertainty on each component taken from the guidelines and from the project’s own measurement:</p>
<div class="cell">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">u</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>SOC_REF <span class="op">=</span> <span class="fl">0.05</span>,   <span class="co"># reference stock, well-sampled cell</span></span>
<span>       F_MG    <span class="op">=</span> <span class="fl">0.09</span>,   <span class="co"># management factor, improved tropical grassland</span></span>
<span>       F_I     <span class="op">=</span> <span class="fl">0.30</span>,   <span class="co"># input factor, high organic input</span></span>
<span>       G       <span class="op">=</span> <span class="fl">0.63</span>,   <span class="co"># biomass accumulation rate, agroforestry</span></span>
<span>       Area    <span class="op">=</span> <span class="fl">0.10</span><span class="op">)</span>   <span class="co"># activity data</span></span>
<span></span>
<span><span class="va">u_total</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">u</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fl">100</span> <span class="op">*</span> <span class="va">u_total</span>, <span class="fl">1</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] 71.2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Seventy-one per cent. That figure is not unusual for a Tier 1 agroforestry estimate, and it is worth sitting with, because it means the honest interval on the claim is wider than the claim itself in one direction.</p>
</section><section id="where-the-uncertainty-actually-lives" class="level2" data-number="8.7"><h2 data-number="8.7" class="anchored" data-anchor-id="where-the-uncertainty-actually-lives">
<span class="header-section-number">8.7</span> Where the uncertainty actually lives</h2>
<p>Quadrature has a property that governs everything about how a project should spend its money, and it is not intuitive. Because the terms are squared before summing, a term’s contribution to the total is proportional to its square, so large terms do not merely dominate, they annihilate the small ones.</p>
<div class="cell">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fl">100</span> <span class="op">*</span> <span class="va">u</span><span class="op">^</span><span class="fl">2</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">u</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span>, <span class="fl">1</span><span class="op">)</span>      <span class="co"># share of total variance</span></span>
<span><span class="co">#&gt; SOC_REF    F_MG     F_I       G    Area </span></span>
<span><span class="co">#&gt;     0.5     1.6    17.7    78.2     2.0</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The biomass accumulation rate contributes seventy-eight per cent of the variance. The reference soil stock contributes half of one per cent. Now ask what improving each one would buy:</p>
<div class="cell">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/lapply.html">sapply</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">u</span><span class="op">)</span>, <span class="kw">function</span><span class="op">(</span><span class="va">k</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="va">v</span> <span class="op">&lt;-</span> <span class="va">u</span>; <span class="va">v</span><span class="op">[</span><span class="va">k</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="va">v</span><span class="op">[</span><span class="va">k</span><span class="op">]</span> <span class="op">/</span> <span class="fl">2</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fl">100</span> <span class="op">*</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">v</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span><span class="op">)</span>, <span class="fl">1</span><span class="op">)</span></span>
<span><span class="op">}</span><span class="op">)</span></span>
<span><span class="co">#&gt; SOC_REF    F_MG     F_I       G    Area </span></span>
<span><span class="co">#&gt;    71.1    70.8    66.3    45.8    70.7</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Halving the uncertainty on the growth rate takes the project from 71 to 46 per cent. Halving the uncertainty on the reference soil stock takes it from 71.2 to 71.1. The comparison becomes starker if you imagine perfect knowledge:</p>
<div class="cell">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/lapply.html">sapply</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">u</span><span class="op">)</span>, <span class="kw">function</span><span class="op">(</span><span class="va">k</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="va">v</span> <span class="op">&lt;-</span> <span class="va">u</span>; <span class="va">v</span><span class="op">[</span><span class="va">k</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="fl">0</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fl">100</span> <span class="op">*</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">v</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span><span class="op">)</span>, <span class="fl">1</span><span class="op">)</span></span>
<span><span class="op">}</span><span class="op">)</span></span>
<span><span class="co">#&gt; SOC_REF    F_MG     F_I       G    Area </span></span>
<span><span class="co">#&gt;    71.1    70.7    64.6    33.3    70.5</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Eliminating the area uncertainty <em>entirely</em>, surveying every boundary to the centimetre and knowing the hectares exactly, moves total uncertainty from 71.2 per cent to 70.5. Eliminating the soil reference stock uncertainty moves it to 71.1.</p>
<p>This is the most actionable result in the chapter, and it cuts against how carbon projects usually allocate effort. Spatial precision is visible, satisfying, and easy to procure. It is also, in a project of this shape, nearly worthless. The money belongs in the growth-rate measurement, which is unglamorous fieldwork on permanent plots, and which no improvement in imagery will ever substitute for.</p>
<p>The general rule follows from the algebra: rank the terms by <span class="math inline">\(U_i^2\)</span>, and work down the list. A term contributing under one per cent of the variance cannot be worth measuring, however cheap, because the total will not move.</p>
</section><section id="what-the-imprecision-costs" class="level2" data-number="8.8"><h2 data-number="8.8" class="anchored" data-anchor-id="what-the-imprecision-costs">
<span class="header-section-number">8.8</span> What the imprecision costs</h2>
<p>Convert it to credits, which is the language the decision is actually made in:</p>
<div class="cell">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">point_estimate</span> <span class="op">&lt;-</span> <span class="fl">18.5</span> <span class="op">*</span> <span class="fl">1000</span>                   <span class="co"># tCO2e/yr over 1,000 ha</span></span>
<span><span class="va">conservative</span>   <span class="op">&lt;-</span> <span class="va">point_estimate</span> <span class="op">*</span> <span class="op">(</span><span class="fl">1</span> <span class="op">-</span> <span class="va">u_total</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>point_estimate <span class="op">=</span> <span class="va">point_estimate</span>,</span>
<span>        conservative   <span class="op">=</span> <span class="va">conservative</span>,</span>
<span>        forgone        <span class="op">=</span> <span class="va">point_estimate</span> <span class="op">-</span> <span class="va">conservative</span>,</span>
<span>        forgone_pct    <span class="op">=</span> <span class="fl">100</span> <span class="op">*</span> <span class="va">u_total</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; point_estimate   conservative        forgone    forgone_pct </span></span>
<span><span class="co">#&gt;          18500           5321          13179             71</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Reporting against the lower bound, the project claims about 5,300 tonnes where its central estimate is 18,500. Thirteen thousand tonnes a year are forgone, not because the carbon is not there, but because the project cannot demonstrate that it is. Under the deduction arithmetic of the uncertainty chapter the loss is smaller and the logic identical.</p>
<p>That number is also the budget available for reducing it. If halving the growth-rate uncertainty costs less than the value of the credits it recovers, the measurement pays for itself, and this calculation is how you find out before commissioning the fieldwork rather than after.</p>
<section id="double-counting-across-timelines" class="level4 unnumbered unlisted verification"><h4 class="unnumbered unlisted anchored" data-anchor-id="double-counting-across-timelines">Double counting across timelines</h4>
<p>The twenty-year transition creates a bookkeeping hazard that catches experienced practitioners. A parcel that changes management in year one is still accruing its stock change in year fifteen. If a second intervention is credited on the same parcel in year eight, part of the soil carbon response may be claimed twice: once against the first transition and once against the second.</p>
<p>The rule is that stock change for a given parcel is computed against a single transition timeline, not per intervention. Where interventions overlap, the parcel carries one trajectory and the later activity is credited only for the increment beyond what the first would have delivered anyway.</p>
<p>Tracking this in practice means the parcel, not the project, is the accounting unit, and each parcel needs the date its transition clock started. Where activity data comes from wall-to-wall mapping rather than parcel records, that date may simply not exist, which is one of the strongest arguments for the transition matrices of IPCC Approach 3 over the aggregate statistics of Approach 1.</p>
</section><section id="which-factors-a-registry-will-accept" class="level4 unnumbered unlisted verification"><h4 class="unnumbered unlisted anchored" data-anchor-id="which-factors-a-registry-will-accept">Which factors a registry will accept</h4>
<p>Standards differ on how much a project may lean on defaults. In general, a Tier 1 default is acceptable where it is conservative for the claim being made, and not otherwise. A default that inflates a crediting claim will be challenged; the same default used to inflate a <em>baseline</em> against which the project is credited is usually accepted without argument, because it works against the proponent.</p>
<p>That asymmetry is worth stating plainly because it is the fastest way to predict which of a project’s factor choices a verifier will scrutinise. Work out, for each factor, whether an error in the direction of the default increases or decreases the credits issued. The ones that increase them are where the questions come.</p>
<p>The uncertainty from this chapter then feeds the deduction machinery compared at the end of the uncertainty chapter. Under ACR it joins the other pool uncertainties in the weighted combination of Equation 22, and is measured against the ten per cent precision requirement. Under ART-TREES and Verra it enters the half-width of the 90 per cent interval directly. A 71 per cent uncertainty is catastrophic under any of them, which is the practical reason Tier 1 agroforestry projects tend to move to Tier 2 growth rates as soon as they can afford to.</p>
</section></section><section id="exercises" class="level2" data-number="8.9"><h2 data-number="8.9" class="anchored" data-anchor-id="exercises">
<span class="header-section-number">8.9</span> Exercises</h2>
<ol type="1">
<li>Recompute the stock change using a cool temperate moist HAC reference stock (81 tC/ha) instead of the tropical moist LAC value, holding the three factors constant. How much does the annual figure move, and what does that say about the cost of misclassifying climate zone?</li>
<li>Using the extract of Table 2.3 above, identify which cells you would be comfortable using in a crediting claim and which you would not. Write one sentence per cell justifying the decision on the basis of the stated uncertainty and sample size.</li>
<li>In the propagation example, suppose better fieldwork reduces the growth-rate uncertainty from 63 to 25 per cent, and that improving the input factor from 30 to 20 per cent costs the same amount. Which would you buy, and by how much does each move the total?</li>
<li>Add a sixth uncertainty term of 15 per cent to the propagation, representing a carbon fraction. Does it change the ranking of where to spend money? Explain in terms of the squared contributions rather than the raw percentages.</li>
<li>The transition period is twenty years for gains and one year for losses. Construct a numerical example of two projects with identical biophysical outcomes but different timings, and show how their reported annual figures differ.</li>
<li>
<em>(Applied.)</em> A project reports 71 per cent uncertainty and a point estimate of 18,500 tCO2e per year. Using the three registry deduction rules from the uncertainty chapter, calculate the credits issued under each. Then state what you would advise the project to measure first.</li>
</ol>


<!-- -->

<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list" style="display: none">
<div id="ref-batjes2011" class="csl-entry" role="listitem">
Batjes, N. H. (2011). Soil organic carbon stocks under native vegetation: Revised estimates for use with the simple assessment option of the carbon benefits project system. <em>Agriculture, Ecosystems and Environment</em>, <em>142</em>(3–4), 365–373. <a href="https://doi.org/10.1016/j.agee.2011.06.007">https://doi.org/10.1016/j.agee.2011.06.007</a>
</div>
<div id="ref-ipcc2006gl" class="csl-entry" role="listitem">
IPCC. (2006). <em>2006 IPCC guidelines for national greenhouse gas inventories, volume 4: Agriculture, forestry and other land use</em>. Institute for Global Environmental Strategies.
</div>
<div id="ref-ipcc2019refinement" class="csl-entry" role="listitem">
IPCC. (2019). <em>2019 refinement to the 2006 IPCC guidelines for national greenhouse gas inventories, volume 4: Agriculture, forestry and other land use</em> (E. Calvo Buendia, K. Tanabe, A. Kranjc, J. Baasansuren, M. Fukuda, S. Ngarize, A. Osako, Y. Pyrozhenko, P. Shermanau, &amp; S. Federici, Eds.). IPCC.
</div>
</div>
</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./allometry.html" class="pagination-link" aria-label="Allometry and Biomass">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Allometry and Biomass</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./activity-data.html" class="pagination-link" aria-label="Activity Data and Classification">
        <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Activity Data and Classification</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb9" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Emission Factors"</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co">  docx:</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="co">    reference-doc: ./references/style.docx</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="co">    highlight-style: github</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="an">execute:</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="co">  eval: true</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="co">  echo: true</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a><span class="co">  warning: false</span></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a><span class="co">  message: false</span></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a><span class="an">knitr:</span></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a><span class="co">  opts_chunk:</span></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a><span class="co">    prefer-html: true</span></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a><span class="co">    dev: "png"</span></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a><span class="co">    dpi: 300</span></span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a><span class="an">bibliography:</span><span class="co"> ./references/references.bib</span></span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a><span class="an">csl:</span><span class="co"> ./references/apa.csl</span></span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a><span class="fu">## The other half of the identity</span></span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a>Almost every greenhouse gas estimate in land use reduces to one multiplication:</span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a>$$\text{Emissions} = \text{Activity Data} \times \text{Emission Factor}$$</span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a>Activity data is the extent of something happening: hectares deforested, hectares converted, hectares under a new management regime. The emission factor is the greenhouse gas consequence per unit of that activity. The previous chapters have been about the left-hand term, because that is where spatial analysis lives. This chapter is about the right-hand one, which is where most of the money and most of the uncertainty actually sit.</span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a>The distinction matters more than it looks. An analyst who maps deforestation to the pixel and then multiplies by a factor pulled from a default table has spent all their effort on the term they measured and none on the term they assumed. The factor is usually the larger source of error, and unlike the map it cannot be improved by better imagery.</span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-31"><a href="#cb9-31" aria-hidden="true" tabindex="-1"></a><span class="fu">## Tiers</span></span>
<span id="cb9-32"><a href="#cb9-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-33"><a href="#cb9-33" aria-hidden="true" tabindex="-1"></a>The IPCC organises methods into three tiers, and the tier is a statement about where the numbers came from rather than about how sophisticated the arithmetic is <span class="co">[</span><span class="ot">@ipcc2006gl</span><span class="co">]</span>.</span>
<span id="cb9-34"><a href="#cb9-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-35"><a href="#cb9-35" aria-hidden="true" tabindex="-1"></a>**Tier 1** uses global or regional default factors published in the guidelines, applied through simple equations, with default assumptions about what happens after a land-use change. It requires no local measurement beyond the activity data. It is the fallback when nothing better exists, and its uncertainties are correspondingly wide.</span>
<span id="cb9-36"><a href="#cb9-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-37"><a href="#cb9-37" aria-hidden="true" tabindex="-1"></a>**Tier 2** keeps the Tier 1 equations but substitutes country-specific or region-specific factors derived from local measurement. This is where most credible national inventories sit.</span>
<span id="cb9-38"><a href="#cb9-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-39"><a href="#cb9-39" aria-hidden="true" tabindex="-1"></a>**Tier 3** replaces the equations themselves with models or direct measurement systems, calibrated and validated locally.</span>
<span id="cb9-40"><a href="#cb9-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-41"><a href="#cb9-41" aria-hidden="true" tabindex="-1"></a>The tiers are not a quality ladder in the sense that Tier 1 is wrong. A well-applied Tier 1 estimate with an honest uncertainty is more defensible than a Tier 3 model whose calibration nobody can reproduce. What the tiers do determine is the size of the interval you must report, and therefore the deduction you must accept.</span>
<span id="cb9-42"><a href="#cb9-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-43"><a href="#cb9-43" aria-hidden="true" tabindex="-1"></a><span class="fu">## Where the default factors come from</span></span>
<span id="cb9-44"><a href="#cb9-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-45"><a href="#cb9-45" aria-hidden="true" tabindex="-1"></a>The Tier 1 defaults are not conjured. They are meta-analyses of published soil and biomass measurements, and the guidelines publish their sample sizes and confidence limits alongside the means. Reading those columns is the single most useful habit in factor selection, because the stated uncertainty varies by more than an order of magnitude across the same table.</span>
<span id="cb9-46"><a href="#cb9-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-47"><a href="#cb9-47" aria-hidden="true" tabindex="-1"></a>This is an extract from the reference soil organic carbon stocks of the 2019 Refinement <span class="co">[</span><span class="ot">@ipcc2019refinement, Table 2.3</span><span class="co">]</span>, which are derived from a global soil profile compilation <span class="co">[</span><span class="ot">@batjes2011</span><span class="co">]</span>. The full table covers ten climate zones by six soil classes; these are seven cells of it.</span>
<span id="cb9-48"><a href="#cb9-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-51"><a href="#cb9-51" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb9-52"><a href="#cb9-52" aria-hidden="true" tabindex="-1"></a>soc_ref <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb9-53"><a href="#cb9-53" aria-hidden="true" tabindex="-1"></a>  <span class="at">climate =</span> <span class="fu">c</span>(<span class="st">"Cool temperate moist"</span>, <span class="st">"Cool temperate moist"</span>, <span class="st">"Warm temperate dry"</span>,</span>
<span id="cb9-54"><a href="#cb9-54" aria-hidden="true" tabindex="-1"></a>              <span class="st">"Tropical moist"</span>, <span class="st">"Tropical moist"</span>, <span class="st">"Tropical dry"</span>, <span class="st">"Boreal moist/dry"</span>),</span>
<span id="cb9-55"><a href="#cb9-55" aria-hidden="true" tabindex="-1"></a>  <span class="at">soil    =</span> <span class="fu">c</span>(<span class="st">"HAC"</span>, <span class="st">"Sandy"</span>, <span class="st">"HAC"</span>, <span class="st">"HAC"</span>, <span class="st">"LAC"</span>, <span class="st">"LAC"</span>, <span class="st">"Sandy"</span>),</span>
<span id="cb9-56"><a href="#cb9-56" aria-hidden="true" tabindex="-1"></a>  <span class="at">socref  =</span> <span class="fu">c</span>(<span class="dv">81</span>, <span class="dv">51</span>, <span class="dv">24</span>, <span class="dv">40</span>, <span class="dv">38</span>, <span class="dv">19</span>, <span class="dv">10</span>),      <span class="co"># tonnes C / ha, 0-30 cm</span></span>
<span id="cb9-57"><a href="#cb9-57" aria-hidden="true" tabindex="-1"></a>  <span class="at">unc_pct =</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">13</span>, <span class="dv">5</span>, <span class="dv">7</span>, <span class="dv">5</span>, <span class="dv">10</span>, <span class="dv">90</span>),          <span class="co"># 95% limit, % of mean</span></span>
<span id="cb9-58"><a href="#cb9-58" aria-hidden="true" tabindex="-1"></a>  <span class="at">n       =</span> <span class="fu">c</span>(<span class="dv">334</span>, <span class="dv">126</span>, <span class="dv">781</span>, <span class="dv">226</span>, <span class="dv">326</span>, <span class="dv">135</span>, <span class="cn">NA</span>))</span>
<span id="cb9-59"><a href="#cb9-59" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(soc_ref)</span>
<span id="cb9-60"><a href="#cb9-60" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-61"><a href="#cb9-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-62"><a href="#cb9-62" aria-hidden="true" tabindex="-1"></a>Look at the last row against the third. Warm temperate dry soils with high activity clay are stated as 24 tonnes per hectare with a 95 per cent limit of five per cent, resting on 781 measured profiles. Boreal sandy soils are stated as 10 tonnes per hectare with a limit of ninety per cent, resting on no profiles at all: that figure is a nominal error assigned because no data were available, carried forward from the 1996 guidelines.</span>
<span id="cb9-63"><a href="#cb9-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-64"><a href="#cb9-64" aria-hidden="true" tabindex="-1"></a>Those two entries look identical in a spreadsheet. They are epistemically unrelated. One is a well-estimated mean; the other is a placeholder with an honesty marker attached. A project whose stratification lands it in the second cell is in a different position from one that lands in the first, and no amount of downstream care recovers the difference.</span>
<span id="cb9-65"><a href="#cb9-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-68"><a href="#cb9-68" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb9-69"><a href="#cb9-69" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">worst_to_best_ratio =</span> <span class="fu">max</span>(soc_ref<span class="sc">$</span>unc_pct) <span class="sc">/</span> <span class="fu">min</span>(soc_ref<span class="sc">$</span>unc_pct))</span>
<span id="cb9-70"><a href="#cb9-70" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-71"><a href="#cb9-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-72"><a href="#cb9-72" aria-hidden="true" tabindex="-1"></a>The stated uncertainty spans eighteenfold within a single table. Factor selection is therefore not a lookup; it is a decision about which of these positions you are willing to defend.</span>
<span id="cb9-73"><a href="#cb9-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-74"><a href="#cb9-74" aria-hidden="true" tabindex="-1"></a><span class="fu">## The stock-difference method</span></span>
<span id="cb9-75"><a href="#cb9-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-76"><a href="#cb9-76" aria-hidden="true" tabindex="-1"></a>Soil carbon is the pool where Tier 1 methods have changed most. The 2006 guidelines assumed that converting land oxidised its soil carbon immediately. The 2019 Refinement replaces that with a linear transition to a new equilibrium spread over a default twenty years, computed as a difference between two stock estimates <span class="co">[</span><span class="ot">@ipcc2019refinement, Eq. 2.25</span><span class="co">]</span>:</span>
<span id="cb9-77"><a href="#cb9-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-78"><a href="#cb9-78" aria-hidden="true" tabindex="-1"></a>$$\Delta C_{Mineral} = \frac{SOC_0 - SOC_{(0-T)}}{D}$$</span>
<span id="cb9-79"><a href="#cb9-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-80"><a href="#cb9-80" aria-hidden="true" tabindex="-1"></a>where $SOC_0$ is the stock in the final year of the inventory period, $SOC_{(0-T)}$ the stock at its beginning, and $D$ the time dependence of the stock change factors, twenty years under Tier 1. Each stock is itself built from a reference value and three dimensionless factors:</span>
<span id="cb9-81"><a href="#cb9-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-82"><a href="#cb9-82" aria-hidden="true" tabindex="-1"></a>$$SOC = SOC_{REF} \times F_{LU} \times F_{MG} \times F_{I}$$</span>
<span id="cb9-83"><a href="#cb9-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-84"><a href="#cb9-84" aria-hidden="true" tabindex="-1"></a>$F_{LU}$ is the land use factor, $F_{MG}$ the management factor, and $F_I$ the input factor, each a multiplier relative to the native reference condition. All are defined for a 30 cm depth, because that is the depth the reference stocks were compiled at, and mixing a factor from one depth convention with a stock from another is a common and invisible error.</span>
<span id="cb9-85"><a href="#cb9-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-88"><a href="#cb9-88" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb9-89"><a href="#cb9-89" aria-hidden="true" tabindex="-1"></a>socref <span class="ot">&lt;-</span> <span class="dv">38</span>      <span class="co"># tropical moist, LAC</span></span>
<span id="cb9-90"><a href="#cb9-90" aria-hidden="true" tabindex="-1"></a>f_lu   <span class="ot">&lt;-</span> <span class="fl">0.83</span>    <span class="co"># forest to long-term cultivated</span></span>
<span id="cb9-91"><a href="#cb9-91" aria-hidden="true" tabindex="-1"></a>f_mg   <span class="ot">&lt;-</span> <span class="fl">1.00</span>    <span class="co"># full tillage</span></span>
<span id="cb9-92"><a href="#cb9-92" aria-hidden="true" tabindex="-1"></a>f_i    <span class="ot">&lt;-</span> <span class="fl">0.94</span>    <span class="co"># low input</span></span>
<span id="cb9-93"><a href="#cb9-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-94"><a href="#cb9-94" aria-hidden="true" tabindex="-1"></a>soc_new    <span class="ot">&lt;-</span> socref <span class="sc">*</span> f_lu <span class="sc">*</span> f_mg <span class="sc">*</span> f_i</span>
<span id="cb9-95"><a href="#cb9-95" aria-hidden="true" tabindex="-1"></a>annual_c   <span class="ot">&lt;-</span> (soc_new <span class="sc">-</span> socref) <span class="sc">/</span> <span class="dv">20</span></span>
<span id="cb9-96"><a href="#cb9-96" aria-hidden="true" tabindex="-1"></a>annual_co2 <span class="ot">&lt;-</span> annual_c <span class="sc">*</span> <span class="dv">44</span> <span class="sc">/</span> <span class="dv">12</span></span>
<span id="cb9-97"><a href="#cb9-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-98"><a href="#cb9-98" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">soc_before =</span> socref, <span class="at">soc_after =</span> soc_new,</span>
<span id="cb9-99"><a href="#cb9-99" aria-hidden="true" tabindex="-1"></a>        <span class="at">tC_ha_yr =</span> annual_c, <span class="at">tCO2e_ha_yr =</span> annual_co2), <span class="dv">3</span>)</span>
<span id="cb9-100"><a href="#cb9-100" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-101"><a href="#cb9-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-102"><a href="#cb9-102" aria-hidden="true" tabindex="-1"></a>The chain matters more than any single link. Three multiplicative factors mean three opportunities for a stratification error, and because they multiply, a mistake in any one of them scales the whole result rather than adding to it.</span>
<span id="cb9-103"><a href="#cb9-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-104"><a href="#cb9-104" aria-hidden="true" tabindex="-1"></a><span class="fu">## The asymmetry nobody mentions</span></span>
<span id="cb9-105"><a href="#cb9-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-106"><a href="#cb9-106" aria-hidden="true" tabindex="-1"></a>Tier 1 does not treat gains and losses alike. Carbon *increases* are spread over the twenty-year transition; carbon *losses* from dead organic matter on conversion are assigned to a single year <span class="co">[</span><span class="ot">@ipcc2019refinement, s.2.3.2</span><span class="co">]</span>. That asymmetry is deliberate and conservative: it credits slowly and debits fast.</span>
<span id="cb9-107"><a href="#cb9-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-108"><a href="#cb9-108" aria-hidden="true" tabindex="-1"></a>It also has a practical consequence for anyone comparing a project's numbers against an inventory. A project reporting a gain over five years captures a quarter of the eventual stock change, not all of it, and a project reporting a conversion loss books the whole thing at once. Two projects with identical biophysical outcomes and different timings will report very different annual figures, entirely legitimately.</span>
<span id="cb9-109"><a href="#cb9-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-110"><a href="#cb9-110" aria-hidden="true" tabindex="-1"></a><span class="fu">## Propagating the uncertainty</span></span>
<span id="cb9-111"><a href="#cb9-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-112"><a href="#cb9-112" aria-hidden="true" tabindex="-1"></a>Each factor in the chain carries its own uncertainty, and they combine. For independent terms entering a product, the proportional uncertainties combine in quadrature:</span>
<span id="cb9-113"><a href="#cb9-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-114"><a href="#cb9-114" aria-hidden="true" tabindex="-1"></a>$$U_{total} = \sqrt{U_1^2 + U_2^2 + \dots + U_n^2}$$</span>
<span id="cb9-115"><a href="#cb9-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-116"><a href="#cb9-116" aria-hidden="true" tabindex="-1"></a>Take a silvopastoral project on a thousand hectares, with the uncertainty on each component taken from the guidelines and from the project's own measurement:</span>
<span id="cb9-117"><a href="#cb9-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-120"><a href="#cb9-120" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb9-121"><a href="#cb9-121" aria-hidden="true" tabindex="-1"></a>u <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">SOC_REF =</span> <span class="fl">0.05</span>,   <span class="co"># reference stock, well-sampled cell</span></span>
<span id="cb9-122"><a href="#cb9-122" aria-hidden="true" tabindex="-1"></a>       <span class="at">F_MG    =</span> <span class="fl">0.09</span>,   <span class="co"># management factor, improved tropical grassland</span></span>
<span id="cb9-123"><a href="#cb9-123" aria-hidden="true" tabindex="-1"></a>       <span class="at">F_I     =</span> <span class="fl">0.30</span>,   <span class="co"># input factor, high organic input</span></span>
<span id="cb9-124"><a href="#cb9-124" aria-hidden="true" tabindex="-1"></a>       <span class="at">G       =</span> <span class="fl">0.63</span>,   <span class="co"># biomass accumulation rate, agroforestry</span></span>
<span id="cb9-125"><a href="#cb9-125" aria-hidden="true" tabindex="-1"></a>       <span class="at">Area    =</span> <span class="fl">0.10</span>)   <span class="co"># activity data</span></span>
<span id="cb9-126"><a href="#cb9-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-127"><a href="#cb9-127" aria-hidden="true" tabindex="-1"></a>u_total <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">sum</span>(u<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb9-128"><a href="#cb9-128" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="dv">100</span> <span class="sc">*</span> u_total, <span class="dv">1</span>)</span>
<span id="cb9-129"><a href="#cb9-129" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-130"><a href="#cb9-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-131"><a href="#cb9-131" aria-hidden="true" tabindex="-1"></a>Seventy-one per cent. That figure is not unusual for a Tier 1 agroforestry estimate, and it is worth sitting with, because it means the honest interval on the claim is wider than the claim itself in one direction.</span>
<span id="cb9-132"><a href="#cb9-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-133"><a href="#cb9-133" aria-hidden="true" tabindex="-1"></a><span class="fu">## Where the uncertainty actually lives</span></span>
<span id="cb9-134"><a href="#cb9-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-135"><a href="#cb9-135" aria-hidden="true" tabindex="-1"></a>Quadrature has a property that governs everything about how a project should spend its money, and it is not intuitive. Because the terms are squared before summing, a term's contribution to the total is proportional to its square, so large terms do not merely dominate, they annihilate the small ones.</span>
<span id="cb9-136"><a href="#cb9-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-139"><a href="#cb9-139" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb9-140"><a href="#cb9-140" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="dv">100</span> <span class="sc">*</span> u<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> <span class="fu">sum</span>(u<span class="sc">^</span><span class="dv">2</span>), <span class="dv">1</span>)      <span class="co"># share of total variance</span></span>
<span id="cb9-141"><a href="#cb9-141" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-142"><a href="#cb9-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-143"><a href="#cb9-143" aria-hidden="true" tabindex="-1"></a>The biomass accumulation rate contributes seventy-eight per cent of the variance. The reference soil stock contributes half of one per cent. Now ask what improving each one would buy:</span>
<span id="cb9-144"><a href="#cb9-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-147"><a href="#cb9-147" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb9-148"><a href="#cb9-148" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(<span class="fu">names</span>(u), <span class="cf">function</span>(k) {</span>
<span id="cb9-149"><a href="#cb9-149" aria-hidden="true" tabindex="-1"></a>  v <span class="ot">&lt;-</span> u; v[k] <span class="ot">&lt;-</span> v[k] <span class="sc">/</span> <span class="dv">2</span></span>
<span id="cb9-150"><a href="#cb9-150" aria-hidden="true" tabindex="-1"></a>  <span class="fu">round</span>(<span class="dv">100</span> <span class="sc">*</span> <span class="fu">sqrt</span>(<span class="fu">sum</span>(v<span class="sc">^</span><span class="dv">2</span>)), <span class="dv">1</span>)</span>
<span id="cb9-151"><a href="#cb9-151" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb9-152"><a href="#cb9-152" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-153"><a href="#cb9-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-154"><a href="#cb9-154" aria-hidden="true" tabindex="-1"></a>Halving the uncertainty on the growth rate takes the project from 71 to 46 per cent. Halving the uncertainty on the reference soil stock takes it from 71.2 to 71.1. The comparison becomes starker if you imagine perfect knowledge:</span>
<span id="cb9-155"><a href="#cb9-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-158"><a href="#cb9-158" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb9-159"><a href="#cb9-159" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(<span class="fu">names</span>(u), <span class="cf">function</span>(k) {</span>
<span id="cb9-160"><a href="#cb9-160" aria-hidden="true" tabindex="-1"></a>  v <span class="ot">&lt;-</span> u; v[k] <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb9-161"><a href="#cb9-161" aria-hidden="true" tabindex="-1"></a>  <span class="fu">round</span>(<span class="dv">100</span> <span class="sc">*</span> <span class="fu">sqrt</span>(<span class="fu">sum</span>(v<span class="sc">^</span><span class="dv">2</span>)), <span class="dv">1</span>)</span>
<span id="cb9-162"><a href="#cb9-162" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb9-163"><a href="#cb9-163" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-164"><a href="#cb9-164" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-165"><a href="#cb9-165" aria-hidden="true" tabindex="-1"></a>Eliminating the area uncertainty *entirely*, surveying every boundary to the centimetre and knowing the hectares exactly, moves total uncertainty from 71.2 per cent to 70.5. Eliminating the soil reference stock uncertainty moves it to 71.1.</span>
<span id="cb9-166"><a href="#cb9-166" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-167"><a href="#cb9-167" aria-hidden="true" tabindex="-1"></a>This is the most actionable result in the chapter, and it cuts against how carbon projects usually allocate effort. Spatial precision is visible, satisfying, and easy to procure. It is also, in a project of this shape, nearly worthless. The money belongs in the growth-rate measurement, which is unglamorous fieldwork on permanent plots, and which no improvement in imagery will ever substitute for.</span>
<span id="cb9-168"><a href="#cb9-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-169"><a href="#cb9-169" aria-hidden="true" tabindex="-1"></a>The general rule follows from the algebra: rank the terms by $U_i^2$, and work down the list. A term contributing under one per cent of the variance cannot be worth measuring, however cheap, because the total will not move.</span>
<span id="cb9-170"><a href="#cb9-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-171"><a href="#cb9-171" aria-hidden="true" tabindex="-1"></a><span class="fu">## What the imprecision costs</span></span>
<span id="cb9-172"><a href="#cb9-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-173"><a href="#cb9-173" aria-hidden="true" tabindex="-1"></a>Convert it to credits, which is the language the decision is actually made in:</span>
<span id="cb9-174"><a href="#cb9-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-177"><a href="#cb9-177" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb9-178"><a href="#cb9-178" aria-hidden="true" tabindex="-1"></a>point_estimate <span class="ot">&lt;-</span> <span class="fl">18.5</span> <span class="sc">*</span> <span class="dv">1000</span>                   <span class="co"># tCO2e/yr over 1,000 ha</span></span>
<span id="cb9-179"><a href="#cb9-179" aria-hidden="true" tabindex="-1"></a>conservative   <span class="ot">&lt;-</span> point_estimate <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> u_total)</span>
<span id="cb9-180"><a href="#cb9-180" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-181"><a href="#cb9-181" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(<span class="at">point_estimate =</span> point_estimate,</span>
<span id="cb9-182"><a href="#cb9-182" aria-hidden="true" tabindex="-1"></a>        <span class="at">conservative   =</span> conservative,</span>
<span id="cb9-183"><a href="#cb9-183" aria-hidden="true" tabindex="-1"></a>        <span class="at">forgone        =</span> point_estimate <span class="sc">-</span> conservative,</span>
<span id="cb9-184"><a href="#cb9-184" aria-hidden="true" tabindex="-1"></a>        <span class="at">forgone_pct    =</span> <span class="dv">100</span> <span class="sc">*</span> u_total))</span>
<span id="cb9-185"><a href="#cb9-185" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb9-186"><a href="#cb9-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-187"><a href="#cb9-187" aria-hidden="true" tabindex="-1"></a>Reporting against the lower bound, the project claims about 5,300 tonnes where its central estimate is 18,500. Thirteen thousand tonnes a year are forgone, not because the carbon is not there, but because the project cannot demonstrate that it is. Under the deduction arithmetic of the uncertainty chapter the loss is smaller and the logic identical.</span>
<span id="cb9-188"><a href="#cb9-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-189"><a href="#cb9-189" aria-hidden="true" tabindex="-1"></a>That number is also the budget available for reducing it. If halving the growth-rate uncertainty costs less than the value of the credits it recovers, the measurement pays for itself, and this calculation is how you find out before commissioning the fieldwork rather than after.</span>
<span id="cb9-190"><a href="#cb9-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-191"><a href="#cb9-191" aria-hidden="true" tabindex="-1"></a>::: {.verification}</span>
<span id="cb9-192"><a href="#cb9-192" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Double counting across timelines {.unnumbered .unlisted}</span></span>
<span id="cb9-193"><a href="#cb9-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-194"><a href="#cb9-194" aria-hidden="true" tabindex="-1"></a>The twenty-year transition creates a bookkeeping hazard that catches experienced</span>
<span id="cb9-195"><a href="#cb9-195" aria-hidden="true" tabindex="-1"></a>practitioners. A parcel that changes management in year one is still accruing its</span>
<span id="cb9-196"><a href="#cb9-196" aria-hidden="true" tabindex="-1"></a>stock change in year fifteen. If a second intervention is credited on the same</span>
<span id="cb9-197"><a href="#cb9-197" aria-hidden="true" tabindex="-1"></a>parcel in year eight, part of the soil carbon response may be claimed twice:</span>
<span id="cb9-198"><a href="#cb9-198" aria-hidden="true" tabindex="-1"></a>once against the first transition and once against the second.</span>
<span id="cb9-199"><a href="#cb9-199" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-200"><a href="#cb9-200" aria-hidden="true" tabindex="-1"></a>The rule is that stock change for a given parcel is computed against a single</span>
<span id="cb9-201"><a href="#cb9-201" aria-hidden="true" tabindex="-1"></a>transition timeline, not per intervention. Where interventions overlap, the</span>
<span id="cb9-202"><a href="#cb9-202" aria-hidden="true" tabindex="-1"></a>parcel carries one trajectory and the later activity is credited only for the</span>
<span id="cb9-203"><a href="#cb9-203" aria-hidden="true" tabindex="-1"></a>increment beyond what the first would have delivered anyway.</span>
<span id="cb9-204"><a href="#cb9-204" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-205"><a href="#cb9-205" aria-hidden="true" tabindex="-1"></a>Tracking this in practice means the parcel, not the project, is the accounting</span>
<span id="cb9-206"><a href="#cb9-206" aria-hidden="true" tabindex="-1"></a>unit, and each parcel needs the date its transition clock started. Where activity</span>
<span id="cb9-207"><a href="#cb9-207" aria-hidden="true" tabindex="-1"></a>data comes from wall-to-wall mapping rather than parcel records, that date may</span>
<span id="cb9-208"><a href="#cb9-208" aria-hidden="true" tabindex="-1"></a>simply not exist, which is one of the strongest arguments for the transition</span>
<span id="cb9-209"><a href="#cb9-209" aria-hidden="true" tabindex="-1"></a>matrices of IPCC Approach 3 over the aggregate statistics of Approach 1.</span>
<span id="cb9-210"><a href="#cb9-210" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb9-211"><a href="#cb9-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-212"><a href="#cb9-212" aria-hidden="true" tabindex="-1"></a>::: {.verification}</span>
<span id="cb9-213"><a href="#cb9-213" aria-hidden="true" tabindex="-1"></a><span class="fu">#### Which factors a registry will accept {.unnumbered .unlisted}</span></span>
<span id="cb9-214"><a href="#cb9-214" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-215"><a href="#cb9-215" aria-hidden="true" tabindex="-1"></a>Standards differ on how much a project may lean on defaults. In general, a Tier 1</span>
<span id="cb9-216"><a href="#cb9-216" aria-hidden="true" tabindex="-1"></a>default is acceptable where it is conservative for the claim being made, and not</span>
<span id="cb9-217"><a href="#cb9-217" aria-hidden="true" tabindex="-1"></a>otherwise. A default that inflates a crediting claim will be challenged; the same</span>
<span id="cb9-218"><a href="#cb9-218" aria-hidden="true" tabindex="-1"></a>default used to inflate a *baseline* against which the project is credited is</span>
<span id="cb9-219"><a href="#cb9-219" aria-hidden="true" tabindex="-1"></a>usually accepted without argument, because it works against the proponent.</span>
<span id="cb9-220"><a href="#cb9-220" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-221"><a href="#cb9-221" aria-hidden="true" tabindex="-1"></a>That asymmetry is worth stating plainly because it is the fastest way to predict</span>
<span id="cb9-222"><a href="#cb9-222" aria-hidden="true" tabindex="-1"></a>which of a project's factor choices a verifier will scrutinise. Work out, for each</span>
<span id="cb9-223"><a href="#cb9-223" aria-hidden="true" tabindex="-1"></a>factor, whether an error in the direction of the default increases or decreases</span>
<span id="cb9-224"><a href="#cb9-224" aria-hidden="true" tabindex="-1"></a>the credits issued. The ones that increase them are where the questions come.</span>
<span id="cb9-225"><a href="#cb9-225" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-226"><a href="#cb9-226" aria-hidden="true" tabindex="-1"></a>The uncertainty from this chapter then feeds the deduction machinery compared at</span>
<span id="cb9-227"><a href="#cb9-227" aria-hidden="true" tabindex="-1"></a>the end of the uncertainty chapter. Under ACR it joins the other pool uncertainties in the</span>
<span id="cb9-228"><a href="#cb9-228" aria-hidden="true" tabindex="-1"></a>weighted combination of Equation 22, and is measured against the ten per cent</span>
<span id="cb9-229"><a href="#cb9-229" aria-hidden="true" tabindex="-1"></a>precision requirement. Under ART-TREES and Verra it enters the half-width of the</span>
<span id="cb9-230"><a href="#cb9-230" aria-hidden="true" tabindex="-1"></a>90 per cent interval directly. A 71 per cent uncertainty is catastrophic under any</span>
<span id="cb9-231"><a href="#cb9-231" aria-hidden="true" tabindex="-1"></a>of them, which is the practical reason Tier 1 agroforestry projects tend to move</span>
<span id="cb9-232"><a href="#cb9-232" aria-hidden="true" tabindex="-1"></a>to Tier 2 growth rates as soon as they can afford to.</span>
<span id="cb9-233"><a href="#cb9-233" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb9-234"><a href="#cb9-234" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-235"><a href="#cb9-235" aria-hidden="true" tabindex="-1"></a><span class="fu">## Exercises</span></span>
<span id="cb9-236"><a href="#cb9-236" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-237"><a href="#cb9-237" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>Recompute the stock change using a cool temperate moist HAC reference stock (81 tC/ha) instead of the tropical moist LAC value, holding the three factors constant. How much does the annual figure move, and what does that say about the cost of misclassifying climate zone?</span>
<span id="cb9-238"><a href="#cb9-238" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>Using the extract of Table 2.3 above, identify which cells you would be comfortable using in a crediting claim and which you would not. Write one sentence per cell justifying the decision on the basis of the stated uncertainty and sample size.</span>
<span id="cb9-239"><a href="#cb9-239" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>In the propagation example, suppose better fieldwork reduces the growth-rate uncertainty from 63 to 25 per cent, and that improving the input factor from 30 to 20 per cent costs the same amount. Which would you buy, and by how much does each move the total?</span>
<span id="cb9-240"><a href="#cb9-240" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>Add a sixth uncertainty term of 15 per cent to the propagation, representing a carbon fraction. Does it change the ranking of where to spend money? Explain in terms of the squared contributions rather than the raw percentages.</span>
<span id="cb9-241"><a href="#cb9-241" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>The transition period is twenty years for gains and one year for losses. Construct a numerical example of two projects with identical biophysical outcomes but different timings, and show how their reported annual figures differ.</span>
<span id="cb9-242"><a href="#cb9-242" aria-hidden="true" tabindex="-1"></a><span class="ss">6. </span>*(Applied.)* A project reports 71 per cent uncertainty and a point estimate of 18,500 tCO2e per year. Using the three registry deduction rules from the uncertainty chapter, calculate the credits issued under each. Then state what you would advise the project to measure first.</span>
</code><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p><a href="https://github.com/seamusrobertmurphy/training-rspatial">Source</a></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/seamusrobertmurphy/training-rspatial/edit/main/emission-factors.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/seamusrobertmurphy/training-rspatial/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>


</body></html>